# Generated by Django 3.1.13 on 2021-07-31 15:32
# Generated models must be modified to set 'managed' : True
# FK Relations must be added manually and sorted by reference order

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idtype', models.IntegerField(primary_key=True, serialize=True)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.PositiveBigIntegerField(primary_key=True, serialize=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('type_idtype', models.ForeignKey('Type', models.DO_NOTHING, db_column='type_idtype')),
                ('user_iduser', models.ForeignKey('User', models.DO_NOTHING, db_column='user_iduser')),
                ('idrecord', models.AutoField(primary_key=True, serialize=True)),
                ('timestamp', models.PositiveBigIntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': True,
            },
        ),
    ]
