# Generated by Django 3.1.13 on 2021-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('idrecord', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('ammount', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idtype', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
